channels:
- defaults
- conda-forge
dependencies:
- python=3.11.5
- mlflow
- torch
- pandas
- pip
- pip:
  - mlflow==2.19.0
  - llama-index
  - llama-index-core
  - llama-index-llms-ollama
  - llama-index-retrievers-bm25
  - llama-index-llms-huggingface
  - llama-index-embeddings-ollama
  - llama-index-vector-stores-chroma
  - llama-index-llms-huggingface-api
  - scikit-learn
  - groq
  - langchain
  - langchain-community
  - einops
  - sentence-transformers
